# Generated by Django 4.2.5 on 2023-09-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_curr', models.CharField(help_text='Input currency', max_length=5)),
                ('to_curr', models.CharField(help_text='Output currency', max_length=5)),
                ('value', models.SmallIntegerField(help_text='Quantity to be converted')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
